package com.guanmu.onehours;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DLINK_TAG_POINT".
*/
public class DLinkTagPointDao extends AbstractDao<DLinkTagPoint, Long> {

    public static final String TABLENAME = "DLINK_TAG_POINT";

    /**
     * Properties of entity DLinkTagPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TagId = new Property(1, String.class, "tagId", false, "TAG_ID");
        public final static Property PointId = new Property(2, String.class, "pointId", false, "POINT_ID");
    }

    private DaoSession daoSession;

    private Query<DLinkTagPoint> dPoint_DLinkTagListQuery;
    private Query<DLinkTagPoint> dTag_DLinkPointListQuery;

    public DLinkTagPointDao(DaoConfig config) {
        super(config);
    }
    
    public DLinkTagPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DLINK_TAG_POINT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TAG_ID\" TEXT NOT NULL ," + // 1: tagId
                "\"POINT_ID\" TEXT NOT NULL );"); // 2: pointId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DLINK_TAG_POINT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DLinkTagPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTagId());
        stmt.bindString(3, entity.getPointId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DLinkTagPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTagId());
        stmt.bindString(3, entity.getPointId());
    }

    @Override
    protected final void attachEntity(DLinkTagPoint entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DLinkTagPoint readEntity(Cursor cursor, int offset) {
        DLinkTagPoint entity = new DLinkTagPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // tagId
            cursor.getString(offset + 2) // pointId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DLinkTagPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTagId(cursor.getString(offset + 1));
        entity.setPointId(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DLinkTagPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DLinkTagPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DLinkTagPoint entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dLinkTagList" to-many relationship of DPoint. */
    public List<DLinkTagPoint> _queryDPoint_DLinkTagList(String pointId) {
        synchronized (this) {
            if (dPoint_DLinkTagListQuery == null) {
                QueryBuilder<DLinkTagPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PointId.eq(null));
                dPoint_DLinkTagListQuery = queryBuilder.build();
            }
        }
        Query<DLinkTagPoint> query = dPoint_DLinkTagListQuery.forCurrentThread();
        query.setParameter(0, pointId);
        return query.list();
    }

    /** Internal query to resolve the "dLinkPointList" to-many relationship of DTag. */
    public List<DLinkTagPoint> _queryDTag_DLinkPointList(String tagId) {
        synchronized (this) {
            if (dTag_DLinkPointListQuery == null) {
                QueryBuilder<DLinkTagPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TagId.eq(null));
                dTag_DLinkPointListQuery = queryBuilder.build();
            }
        }
        Query<DLinkTagPoint> query = dTag_DLinkPointListQuery.forCurrentThread();
        query.setParameter(0, tagId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDPointDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getDTagDao().getAllColumns());
            builder.append(" FROM DLINK_TAG_POINT T");
            builder.append(" LEFT JOIN DPOINT T0 ON T.\"POINT_ID\"=T0.\"GUID\"");
            builder.append(" LEFT JOIN DTAG T1 ON T.\"TAG_ID\"=T1.\"GUID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DLinkTagPoint loadCurrentDeep(Cursor cursor, boolean lock) {
        DLinkTagPoint entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DPoint dPoint = loadCurrentOther(daoSession.getDPointDao(), cursor, offset);
         if(dPoint != null) {
            entity.setDPoint(dPoint);
        }
        offset += daoSession.getDPointDao().getAllColumns().length;

        DTag dTag = loadCurrentOther(daoSession.getDTagDao(), cursor, offset);
         if(dTag != null) {
            entity.setDTag(dTag);
        }

        return entity;    
    }

    public DLinkTagPoint loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DLinkTagPoint> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DLinkTagPoint> list = new ArrayList<DLinkTagPoint>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DLinkTagPoint> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DLinkTagPoint> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
