package com.guanmu.onehours;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DLINK_TASK_POINT".
*/
public class DLinkTaskPointDao extends AbstractDao<DLinkTaskPoint, Long> {

    public static final String TABLENAME = "DLINK_TASK_POINT";

    /**
     * Properties of entity DLinkTaskPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TaskId = new Property(1, String.class, "taskId", false, "TASK_ID");
        public final static Property PointId = new Property(2, String.class, "pointId", false, "POINT_ID");
    }

    private DaoSession daoSession;

    private Query<DLinkTaskPoint> dPoint_DLinkTaskListQuery;
    private Query<DLinkTaskPoint> dTask_DLinkPointListQuery;

    public DLinkTaskPointDao(DaoConfig config) {
        super(config);
    }
    
    public DLinkTaskPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DLINK_TASK_POINT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TASK_ID\" TEXT NOT NULL ," + // 1: taskId
                "\"POINT_ID\" TEXT NOT NULL );"); // 2: pointId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DLINK_TASK_POINT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DLinkTaskPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTaskId());
        stmt.bindString(3, entity.getPointId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DLinkTaskPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTaskId());
        stmt.bindString(3, entity.getPointId());
    }

    @Override
    protected final void attachEntity(DLinkTaskPoint entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DLinkTaskPoint readEntity(Cursor cursor, int offset) {
        DLinkTaskPoint entity = new DLinkTaskPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // taskId
            cursor.getString(offset + 2) // pointId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DLinkTaskPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTaskId(cursor.getString(offset + 1));
        entity.setPointId(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DLinkTaskPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DLinkTaskPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DLinkTaskPoint entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dLinkTaskList" to-many relationship of DPoint. */
    public List<DLinkTaskPoint> _queryDPoint_DLinkTaskList(String pointId) {
        synchronized (this) {
            if (dPoint_DLinkTaskListQuery == null) {
                QueryBuilder<DLinkTaskPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PointId.eq(null));
                dPoint_DLinkTaskListQuery = queryBuilder.build();
            }
        }
        Query<DLinkTaskPoint> query = dPoint_DLinkTaskListQuery.forCurrentThread();
        query.setParameter(0, pointId);
        return query.list();
    }

    /** Internal query to resolve the "dLinkPointList" to-many relationship of DTask. */
    public List<DLinkTaskPoint> _queryDTask_DLinkPointList(String taskId) {
        synchronized (this) {
            if (dTask_DLinkPointListQuery == null) {
                QueryBuilder<DLinkTaskPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TaskId.eq(null));
                dTask_DLinkPointListQuery = queryBuilder.build();
            }
        }
        Query<DLinkTaskPoint> query = dTask_DLinkPointListQuery.forCurrentThread();
        query.setParameter(0, taskId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDTaskDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getDPointDao().getAllColumns());
            builder.append(" FROM DLINK_TASK_POINT T");
            builder.append(" LEFT JOIN DTASK T0 ON T.\"TASK_ID\"=T0.\"GUID\"");
            builder.append(" LEFT JOIN DPOINT T1 ON T.\"POINT_ID\"=T1.\"GUID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DLinkTaskPoint loadCurrentDeep(Cursor cursor, boolean lock) {
        DLinkTaskPoint entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DTask dTask = loadCurrentOther(daoSession.getDTaskDao(), cursor, offset);
         if(dTask != null) {
            entity.setDTask(dTask);
        }
        offset += daoSession.getDTaskDao().getAllColumns().length;

        DPoint dPoint = loadCurrentOther(daoSession.getDPointDao(), cursor, offset);
         if(dPoint != null) {
            entity.setDPoint(dPoint);
        }

        return entity;    
    }

    public DLinkTaskPoint loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DLinkTaskPoint> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DLinkTaskPoint> list = new ArrayList<DLinkTaskPoint>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DLinkTaskPoint> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DLinkTaskPoint> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
